# Site settings
title : Csound 
description:
  Community website for the Csound project.
tagline: A Sound and Music Computing System
author :
  name : Csound 
  email : csound
  github : csound 
  
# baseurl: "/cs-site-2024" # the subpath of your site, e.g. /blog/
# url: "https://joachimheintz.github.io" # the base hostname & protocol for your site

sass:
  load_paths:
    - assets/css/*
    
markdown: GFM
  

# do not use these files to build on gihub pages
exclude: ["README.md", "site-internals.md", "changelog.md"]
