# Site settings
title : Csound 
tagline: A Sound and Music Computing System
author :
  name : Csound 
  email : csound
  github : csound 

# Build settings
lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

description:
  Community website for the Csound project.
  
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# do not use these files to build on gihub pages
exclude: ["README.md", "site-internals.md", "changelog.md"]
