# Site settings
title : Csound 
tagline: A Sound and Music Computing System
author :
  name : Csound 
  email : csound
  github : csound 

description: > # this means to ignore newlines until "baseurl:"
  Community website for the Csound project.
  
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# do not use these files to build on gihub pages
exclude: ["README.md", "site-internals.md", "changelog.md"]
