# Site settings
title : Csound 
description:
  Community website for the Csound project.
tagline: A Sound and Music Computing System
author :
  name : Csound 
  email : csound
  github : csound 

favicon: assets/img/favicon.png
  
# this is take from the previous website version
# not sure it is still needed, but probably for posts 
# (jh 2024/04/01)
# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

# sass compiler for syntax highlighting
sass:
  load_paths:
    - assets/css/*
    
# markdown is github flavored markdown
markdown: GFM
  
# files excluded to build on gihub pages
exclude: ["README.md"]
